//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_checkout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_checkout()
        {
            this.tb_orderDetails = new HashSet<tb_orderDetails>();
            this.tb_reterned = new HashSet<tb_reterned>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> bill_id { get; set; }
        public Nullable<int> ship_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string check_code { get; set; }
        public string type { get; set; }
    
        public virtual tb_billinfo tb_billinfo { get; set; }
        public virtual tb_ship tb_ship { get; set; }
        public virtual tb_Users tb_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orderDetails> tb_orderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_reterned> tb_reterned { get; set; }
    }
}
